trigger: none

resources:
  repositories:
    - repository: Stock-Prediction
      type: git
      name: Arun9429/Stock-Prediction
      endpoint: github.com_Arun9429

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: DockerBuildPush
        displayName: 'Build and Push Docker Image'
        pool:
          name: 'azureagents'
        steps:
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: 'dockerhub-connection'
              repository: 'arunce94/stock-price-prediction'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest